### ISSUE TITLE
Erlang.RPC

### ISSUE THREAD

**Issue by 5HT** [lenary/idris-erlang#2]
can't find Erlang.RPC module

``` sh
Can't find import Erlang/RPC
```

**Comment by lenary** [comment]
Hmm. Let me check this out, I'll try to get everything building and working again this weekend.

**Comment by lenary** [comment]
Fixed by 188d6228b4affd82149fbc4cf6f7409527fa790f

Yes, terrible fix, i want to replace the RPC stuff but to be honest I need to think about everything a lot more before I do.
